import { StyleSheet, Dimensions } from "react-native";
import { black, grey, primary, red, white } from "../assets/colors";
import fonts from "../assets/fonts";


const {width: screenWidth, height: screenHieght} = Dimensions.get('window');

const styles = StyleSheet.create({
    main_view: {
      display: 'flex',
      minHeight: screenHieght,
      width: screenWidth,
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      paddingLeft: 40,
      paddingRight: 40,
    },
    loading_text: {
        fontSize: 16,
        fontFamily: fonts.Poppins_500Medium,
        letterSpacing: 1,
        color: primary,
    },
    login_input: {
        width: '100%',
        height: 45,
        fontSize: 18,
        letterSpacing: 1,
        fontFamily: fonts.Poppins_300Light,
        borderBottomWidth: 1,
        marginBottom: 5,
        marginTop: 20,
    },
    login_button: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: 45,
        backgroundColor: primary,
        borderRadius: 5,
        marginTop: 30,
    },
    login_button_text: {
        fontSize: 18,
        fontWeight: '500',
        color: white,
        letterSpacing: 1,
        fontFamily: fonts.Poppins_600SemiBold,
    },
    login_input_error: {
        fontSize: 11,
        fontWeight: '300',
        color: red,
        letterSpacing: 1,
        fontFamily: fonts.Poppins_300Light,
        marginTop: 5,
        marginBottom: 5,
        alignSelf: 'flex-start'
    },
    confirm_message_text: {
        fontSize: 24,
        fontWeight: '600',
        color: primary,
        letterSpacing: 1,
        fontFamily: fonts.Poppins_500Medium,
    },
    confirm_button: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '40%',
        height: 45,
        backgroundColor: primary,
        borderRadius: 5,
        marginTop: 10,
    },
    confirm_button_holder: {
        display: 'flex',
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 20,
    },
    confirm_modal: {
        display: 'flex',
        height: screenHieght,
        width: screenWidth,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: white,
        position: 'absolute',
        top: 0,
        left: 0,
    },
    main_nav_view: {
      display: 'flex',
      minHeight: screenHieght,
      width: screenWidth,
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      paddingLeft: 20,
      paddingRight: 20,
    },
    title_holder: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        justifyContent:'center',
        alignItems: 'center',
        marginTop: 40,
        marginBottom: 40,
    },
    title_text: {
        fontSize: 24,
        fontStyle: 'normal',
        fontFamily: fonts.Poppins_400Regular,
        fontWeight: '400',
        color: primary,
        textAlign: 'center',
    },
    drawer_profile_holder: {
        display: 'flex',
        width: '100%',
        height: 220,
        justifyContent: 'center',
        alignItems: 'center',
    },
    profile_picture: {
        width: 100,
        height: 100,
        resizeMode: 'contain',
        borderRadius: 50,
    },
    divider: {
        width: '60%',
        height: 1,
        backgroundColor: grey,
        alignSelf: 'center',
        marginBottom: 20,
    },
    first_link: {
        width: '100%',
        height: 45,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    link_holder: {
        width: '100%',
        height: 45,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
    },
    link_text: {
        fontSize: 18,
        fontStyle: 'normal',
        fontWeight: '500',
        fontFamily: fonts.Poppins_500Medium,
        color: black,
    },
    links_view: {
        display:'flex',
        width: '100%',
        flexDirection: 'column',
        padding: 20,
    },
    action_button_holder: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        alignItems: 'center',
        marginTop: 10,
    },
    circl_box_holder: {
        width: 80,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    circl_box_text: {
        fontSize: 12,
        fontWeight: '300',
        fontStyle: 'normal',
        fontFamily: fonts.Poppins_300Light,
        color: black,
        marginTop: 5,
    },
    circle_box: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: primary,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    full_column_view: {
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    bottom_box: {
        display: 'flex',
        width: '100%',
        height: 100,
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft: 35,
        backgroundColor: primary,
        alignSelf: 'baseline',
    },
    bottom_box_cirlce: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: white,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    column_holder: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    refresh_text: {
        fontSize: 12,
        fontStyle: 'normal',
        fontFamily: fonts.Poppins_600SemiBold,
        color: white,
        letterSpacing: -1,
        marginTop: 5,
    },
    top_nav_holder: {
        display: 'flex',
        flexDirection: 'row',
        marginTop: 45,
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
        alignSelf: 'flex-start',
        marginBottom: 10,
    },
    top_nav_title: {
        fontSize: 24,
        fontFamily: fonts.Poppins_600SemiBold,
        fontWeight: '600',
        color: primary,
        letterSpacing: 1,
    },
    image_box_holder: {
        display: 'flex',
        width: '100%',
        height: 120,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 60,
        marginBottom: 40,
    },
    profile_page_picture: {
        width: 200,
        height: 200,
        borderRadius: 100,
        resizeMode: 'contain',
    },
  });

  export default styles;